[tools]
yamlfmt = "0.21.0"
tombi = "1.4.0"
"aqua:numtide/treefmt" = "2.5.0"
"cargo:flip-link" = "0.1.12"
"cargo:cargo-binutils" = "0.4.0"
"cargo:cargo-hex-to-uf2" = "0.1.2"

[tasks.build]
description = "Build dongle central and left/right peripheral firmware"
run = "cargo build --release"

[tasks.hex]
description = "Generate Intel HEX images"
depends = ["build"]
run = [
  "cargo objcopy --release --bin central -- -O ihex prospector-central.hex",
  "cargo objcopy --release --bin peripheral_left -- -O ihex cornix-left.hex",
  "cargo objcopy --release --bin peripheral_right -- -O ihex cornix-right.hex",
]

[tasks.uf2]
description = "Generate uf2 images"
depends = ["hex"]
run = [
  "cargo hex-to-uf2 --input-path prospector-central.hex --output-path prospector-central.uf2 --family nrf52840",
  "cargo hex-to-uf2 --input-path cornix-left.hex --output-path cornix-left.uf2 --family nrf52840",
  "cargo hex-to-uf2 --input-path cornix-right.hex --output-path cornix-right.uf2 --family nrf52840",
]

[tasks.lint]
description = "Run clippy linter"
run = "cargo clippy --all-features -- -D warnings"

[tasks.fmt]
description = "Run treefmt"
run = "treefmt --tree-root . --walk filesystem --fail-on-change"
